# Generated by Django 4.1.2 on 2022-10-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.person')),
                ('family_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono familiar')),
                ('medical_treatment', models.BooleanField(blank=True, null=True, verbose_name='Tratamiento médico')),
                ('medications', models.TextField(blank=True, max_length=200, null=True, verbose_name='Medicamentos')),
                ('allergies', models.TextField(blank=True, max_length=200, null=True, verbose_name='Alergias')),
                ('observations', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('school_cert_destinty', models.CharField(blank=True, max_length=30, null=True, verbose_name='Destino de certificado escolar')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('leaving_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('trips_auth', models.BooleanField(default=False, verbose_name='Autorización de paseos')),
                ('medical_auth', models.BooleanField(default=False, verbose_name='Autorización médica')),
                ('leave_auth', models.BooleanField(default=False, verbose_name='Autorización de salida')),
                ('public_auth', models.BooleanField(default=False, verbose_name='Autorización para publicar')),
            ],
            bases=('administracion.person',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.person')),
                ('profession', models.CharField(blank=True, max_length=15, null=True, verbose_name='Profesión')),
                ('job_address', models.CharField(blank=True, max_length=30, null=True, verbose_name='Domicilio laboral')),
                ('job_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono laboral')),
            ],
            bases=('administracion.person',),
        ),
        migrations.CreateModel(
            name='Student_Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Tutor legal', 'Tutor legal')], default='Tutor legal', max_length=15, verbose_name='Vínculo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.student', verbose_name='Alumno')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.tutor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='student_tutor',
            constraint=models.UniqueConstraint(fields=('tutor', 'student'), name='tutor_student_combination'),
        ),
    ]
