# Generated by Django 4.1.2 on 2022-10-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw_Authorized',
            fields=[
                ('doc_number', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='DNI')),
                ('name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nombre')),
                ('lastname', models.CharField(blank=True, max_length=15, null=True, verbose_name='Apellido')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.student', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Autorizado',
                'verbose_name_plural': 'Autorizados',
            },
        ),
        migrations.CreateModel(
            name='Student_Withdraw_Authorized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('Hermano/a', 'Hermano/a'), ('Primo/a', 'Primo/a'), ('Tío/a', 'Tío/a'), ('Otro', 'Otro')], default='Hermano/a', max_length=15, verbose_name='Vínculo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.student', verbose_name='Alumno')),
                ('withdraw_authorized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.withdraw_authorized', verbose_name='Autorizado a retiro')),
            ],
            options={
                'verbose_name': 'Autorizado_Alumno',
                'verbose_name_plural': 'Autorizados_Alumnos',
            },
        ),
        migrations.AddConstraint(
            model_name='student_withdraw_authorized',
            constraint=models.UniqueConstraint(fields=('withdraw_authorized', 'student'), name='authorized_student_combination'),
        ),
    ]
