# Generated by Django 4.1.2 on 2022-10-27 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_remove_withdraw_authorized_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('1', 'Cuota mensual'), ('2', 'Pago de matrícula')], default='1', max_length=1, verbose_name='Tipo de pago')),
                ('unit_amount', models.IntegerField(blank=True, null=True, verbose_name='Monto unitario')),
                ('brothers_qty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1, verbose_name='Cantidad de hermanos')),
                ('brothers_discount', models.IntegerField(blank=True, null=True, verbose_name='Descuento por hermanos')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Payment_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.payment', verbose_name='Pago')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.student', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Pago_Alumno',
                'verbose_name_plural': 'Pagos_Alumnos',
            },
        ),
        migrations.AddConstraint(
            model_name='payment_student',
            constraint=models.UniqueConstraint(fields=('payment', 'student'), name='payment_student_combination'),
        ),
    ]
