# Generated by Django 4.1.2 on 2022-10-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_documents_role_alter_documents_document_type'),
        ('alumnos', '0004_payment_payment_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d', verbose_name='Documento')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.documents', verbose_name='Documentación')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.student', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Docente_Documento',
                'verbose_name_plural': 'Docentes_Documentos',
            },
        ),
    ]
