# Generated by Django 4.1.2 on 2022-10-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alter_student_documents_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_treatment',
            field=models.BooleanField(default=False, verbose_name='Tratamiento médico'),
        ),
    ]
