# Generated by Django 4.1.2 on 2022-10-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alter_student_medical_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_treatment',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tratamiento médico'),
        ),
    ]
