# Generated by Django 4.1.2 on 2022-10-23 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0003_remove_alumno_persona_ptr_remove_tutor_persona_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('telefono_familiar', models.CharField(blank=True, max_length=15, null=True)),
                ('tratamiento_medico', models.BooleanField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, max_length=200, null=True)),
                ('alergias', models.TextField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=200, null=True)),
                ('cert_escolar_destino', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('aut_paseos', models.BooleanField(default=False)),
                ('aut_medica', models.BooleanField(default=False)),
                ('aut_salida', models.BooleanField(default=False)),
                ('aut_publica', models.BooleanField(default=False)),
            ],
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('Profesion', models.CharField(blank=True, max_length=15, null=True)),
                ('domicilio_laboral', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono_laboral', models.CharField(blank=True, max_length=12, null=True)),
            ],
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Tutor_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(choices=[('Madre', 'Madre'), ('Padre', 'Padre'), ('Tutor legal', 'Tutor legal')], default='Tutor legal', max_length=15)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.tutor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tutor_alumno',
            constraint=models.UniqueConstraint(fields=('tutor', 'alumno'), name='tutor_alumno_combinacion'),
        ),
    ]
