# Generated by Django 4.2.1 on 2023-08-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('docentes', '0001_initial'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position_teacher',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='position',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='grade',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.division', verbose_name='División'),
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.level', verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='grade',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.speciality', verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='course_subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.course', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='course_subject',
            name='position_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.position_teacher', verbose_name='Cargo_Docente'),
        ),
        migrations.AddField(
            model_name='course_subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.subject', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='course_student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.course', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='course_student',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.student', verbose_name='Alumno'),
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.grade', verbose_name='Año'),
        ),
        migrations.AddConstraint(
            model_name='position_teacher',
            constraint=models.UniqueConstraint(fields=('position', 'position_type'), name='position_type_combination'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('name', 'division'), name='name_division_combination'),
        ),
        migrations.AddConstraint(
            model_name='course_subject',
            constraint=models.UniqueConstraint(fields=('course', 'subject'), name='course_subject_combination'),
        ),
        migrations.AddConstraint(
            model_name='course_student',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='course_student_combination'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('grade', 'academic_year'), name='id_course_combination'),
        ),
    ]
