# Generated by Django 4.2 on 2023-04-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='course_student',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='division',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='level',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='position',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='position_teacher',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='deleted_date',
        ),
    ]
