# Generated by Django 4.2 on 2023-04-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_remove_bank_deleted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='shortName',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Nombre_corto'),
        ),
    ]
