# Generated by Django 4.2 on 2023-04-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_speciality_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nombre'),
        ),
    ]
