# Generated by Django 4.1.2 on 2022-10-27 23:46

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Nacionalidad'),
        ),
    ]
