# Generated by Django 4.1.2 on 2022-10-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_person_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='doc_number',
            field=models.CharField(max_length=13, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marital_status',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo/a', 'Viudo/a'), ('No aplica', 'No aplica')], default='No aplica', max_length=20, null=True, verbose_name='Estado civil'),
        ),
    ]
