# Generated by Django 4.1.3 on 2022-11-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_person_address_state_person_cp_person_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('3', 'Masculino'), ('4', 'Femenino'), ('2', 'Sin genero'), ('1', 'Sin especificar')], default='Sin especificar', max_length=20, verbose_name='Género'),
        ),
    ]
