# Generated by Django 4.1.3 on 2022-11-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_place',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('3', 'Masculino'), ('4', 'Femenino'), ('2', 'Sin genero'), ('1', 'Sin especificar')], default='Sin especificar', max_length=1, null=True, verbose_name='Género'),
        ),
    ]
