# Generated by Django 4.1.2 on 2022-10-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('email_institucional', models.EmailField(blank=True, max_length=40, null=True)),
                ('telefono_familiar', models.CharField(blank=True, max_length=15, null=True)),
                ('tratamiento_medico', models.BooleanField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, max_length=200, null=True)),
                ('alergias', models.TextField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=200, null=True)),
                ('cert_escolar_destino', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('aut_paseos', models.BooleanField(blank=True, null=True)),
                ('aut_medica', models.BooleanField(blank=True, null=True)),
                ('aut_salida', models.BooleanField(blank=True, null=True)),
                ('aut_publica', models.BooleanField(blank=True, null=True)),
            ],
            bases=('administracion.persona',),
        ),
    ]
