# Generated by Django 4.1.2 on 2022-10-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('dni_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.alumno')),
                ('id_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.curso')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cursoalumnos',
            constraint=models.UniqueConstraint(fields=('id_curso', 'dni_alumno'), name='curso_alumno_combinacion'),
        ),
    ]
