# Generated by Django 4.1.2 on 2022-10-23 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='persona_ptr',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='persona_ptr',
        ),
        migrations.RemoveField(
            model_name='tutor_alumno',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='tutor_alumno',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='docente',
        ),
    ]
