# Generated by Django 4.1.2 on 2022-10-23 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_remove_alumno_persona_ptr_remove_tutor_persona_ptr_and_more'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso_alumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.DeleteModel(
            name='Tutor_Alumno',
        ),
    ]
