# Generated by Django 4.1.2 on 2022-10-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_materia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='user_id',
            new_name='user',
        ),
    ]
