# Generated by Django 4.2.1 on 2023-08-14 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='person',
            name='address_city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='person',
            name='cp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='person',
            name='floor',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_place',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Sin género', 'Sin género'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=15, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
