# Generated by Django 4.2.1 on 2023-08-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_person_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='deleted_date',
            field=models.DateField(null=True, verbose_name='Fecha de eliminación'),
        ),
    ]
