# Generated by Django 4.1.3 on 2022-11-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address_state',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='person',
            name='cp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='person',
            name='floor',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Calle'),
        ),
    ]
