# Generated by Django 4.1.3 on 2023-04-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_person_address_state_alter_person_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address_city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Sin género', 'Sin género'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=15, null=True, verbose_name='Género'),
        ),
    ]
