# Generated by Django 4.2 on 2023-04-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_person_address_city_alter_person_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='deleted_date',
        ),
    ]
