# Generated by Django 4.1.2 on 2022-10-24 21:10

import apps.administracion.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), apps.administracion.models.max_value_current_year], verbose_name='Año lectivo')),
                ('shift', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche'), ('Sin definir', 'Sin definir')], default='Sin definir', max_length=11, verbose_name='Turno')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('N/A', 'N/A')], default='N/A', max_length=8, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('Certificado', 'Certificado'), ('Constancia 1', 'Constancia 1'), ('Constancia 2', 'Constancia 2')], default='DNI', max_length=15, verbose_name='Tipo de documentación')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Primer nombre')),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Segundo nombre')),
                ('first_lastname', models.CharField(max_length=15, verbose_name='Primer apellido')),
                ('second_lastname', models.CharField(blank=True, max_length=15, null=True, verbose_name='Segundo apellido')),
                ('doc_number', models.CharField(max_length=13, verbose_name='DNI')),
                ('personal_email', models.EmailField(blank=True, max_length=40, null=True, verbose_name='Email personal')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('birth_place', models.CharField(blank=True, max_length=15, null=True, verbose_name='Lugar de nacimiento')),
                ('nationality', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nacionalidad')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Sin genero', 'Sin genero'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=20, verbose_name='Género')),
                ('address', models.CharField(blank=True, max_length=15, null=True, verbose_name='Dirección')),
                ('neighborhood', models.CharField(blank=True, max_length=15, null=True, verbose_name='Barrio')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nro de teléfono')),
                ('marital_status', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo/a', 'Viudo/a'), ('No aplica', 'No aplica')], default='No aplica', max_length=20, verbose_name='Estado civil')),
                ('created_date', models.DateField(verbose_name='Fecha de alta')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('N/A', 'N/A')], default='N/A', max_length=8, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('leaving_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre de materia')),
                ('created_date', models.DateField(verbose_name='Fecha de creación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.person')),
                ('cuil', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('seniority_date', models.DateField(blank=True, null=True, verbose_name='Fecha de antiguedad')),
                ('seniority_qty', models.IntegerField(blank=True, null=True, verbose_name='Antiguedd reconocida')),
                ('statistics', models.CharField(choices=[('En actividad', 'En actividad'), ('Tareas pasivas', 'Tareas pasivas'), ('Docentes afectados al JIF pero de otra POF', 'Docentes afectados al JIF pero de otra POF'), ('Docentes del JIF afectados a otro establecimiento', 'Docentes del JIF afectados a otro establecimiento'), ('Sin subvención', 'Sin subvención'), ('Baja', 'Baja'), ('Fuera de actividad', 'InaFuera de actividadctivo'), ('A.T. / Integrador', 'A.T. / Integrador'), ('Par pedagógico / Dep. de dirección privada', 'Par pedagógico / Dep. de dirección privada')], default='En actividad', max_length=50, verbose_name='Estadística')),
            ],
            bases=('administracion.person',),
        ),
        migrations.CreateModel(
            name='Teacher_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.documents', verbose_name='Documentación')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.role', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8, verbose_name='Estado')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.division', verbose_name='División')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.level', verbose_name='Nivel')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.speciality', verbose_name='Modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('leaving_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.course', verbose_name='Curso')),
            ],
        ),
    ]
