# Generated by Django 4.1.2 on 2022-10-27 12:47

import apps.administracion.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), apps.administracion.models.max_value_current_year], verbose_name='Año lectivo')),
                ('shift', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche'), ('Sin definir', 'Sin definir')], default='Sin definir', max_length=11, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Nombre')),
                ('state', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'División',
                'verbose_name_plural': 'Divisiones',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('Certificado', 'Certificado'), ('Constancia 1', 'Constancia 1'), ('Constancia 2', 'Constancia 2')], default='DNI', max_length=15, verbose_name='Tipo de documentación')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('state', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('state', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('N/A', 'N/A')], default='N/A', max_length=8, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('leaving_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre de materia')),
                ('created_date', models.DateField(verbose_name='Fecha de creación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de eliminación')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('state', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8, verbose_name='Estado')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.division', verbose_name='División')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.level', verbose_name='Nivel')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.speciality', verbose_name='Modalidad')),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
            },
        ),
        migrations.CreateModel(
            name='Course_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('leaving_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Curso_Alumno',
                'verbose_name_plural': 'Cursos_Alumnos',
            },
        ),
    ]
