# Generated by Django 4.1.2 on 2022-10-27 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_student',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.student', verbose_name='Alumno'),
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.grade', verbose_name='Año'),
        ),
        migrations.AddConstraint(
            model_name='course_student',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='course_student_combination'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('grade', 'academic_year'), name='id_course_combination'),
        ),
    ]
