# Generated by Django 4.1.2 on 2022-10-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(verbose_name='Código de categoría', primary_key=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_number1', models.IntegerField(blank=True, null=True, verbose_name='Nro de plaza 1')),
                ('place_number2', models.IntegerField(blank=True, null=True, verbose_name='Nro de plaza 2')),
                ('hours_qty', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de horas')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
    ]
