# Generated by Django 4.1.2 on 2022-10-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='speciality',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='status',
            new_name='state',
        ),
    ]
