# Generated by Django 4.1.2 on 2022-10-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_category_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de categoría'),
        ),
    ]
