# Generated by Django 4.1.2 on 2022-10-24 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_rename_status_division_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='state',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.division', verbose_name='División'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.speciality', verbose_name='Modalidad'),
        ),
    ]
