# Generated by Django 4.1.2 on 2022-10-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_grade_division_alter_grade_speciality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='course_student',
            options={'verbose_name': 'Curso_Alumno', 'verbose_name_plural': 'Cursos_Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'División', 'verbose_name_plural': 'Divisiones'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Año', 'verbose_name_plural': 'Años'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Nivel', 'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Modalidad', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='teacher_documents',
            options={'verbose_name': 'Docente_Documento', 'verbose_name_plural': 'Docentes_Documentos'},
        ),
    ]
