# Generated by Django 4.1.2 on 2022-10-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_grade_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('name', 'division'), name='name_division_combination'),
        ),
    ]
