# Generated by Django 4.1.2 on 2022-10-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_position_teacher'),
        ('administracion', '0007_grade_name_division_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('leaving_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.course', verbose_name='Curso')),
                ('position_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.position_teacher', verbose_name='Cargo_Docente')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.subject', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Curso_Materia',
                'verbose_name_plural': 'Cursos_Materias',
            },
        ),
        migrations.AddConstraint(
            model_name='course_subject',
            constraint=models.UniqueConstraint(fields=('course', 'subject'), name='course_subject_combination'),
        ),
    ]
