# Generated by Django 4.1.2 on 2022-10-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('administracion', '0008_course_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='Usuarios'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(max_length=15, unique=True, verbose_name='Tipo de documento'),
        ),
    ]
