# Generated by Django 4.1.2 on 2022-10-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_documents_role_alter_documents_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(max_length=30, unique=True, verbose_name='Tipo de documento'),
        ),
    ]
