# Generated by Django 4.1.2 on 2022-10-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_category_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
