# Generated by Django 4.1.2 on 2022-11-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0010_historicaldisponibility_disponibility'),
        ('administracion', '0013_position_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('Titular', 'Titular'), ('Suplente', 'Suplente'), ('Vacante', 'Vacante')], default='Vacante', max_length=8, verbose_name='Tipo de cargo')),
                ('condition', models.CharField(blank=True, max_length=15, null=True, verbose_name='Situación')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('delete_motive', models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo de baja')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.position', verbose_name='Cargo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Cargo_Docente',
                'verbose_name_plural': 'Cargos_Docentes',
            },
        ),
        migrations.AlterField(
            model_name='course_subject',
            name='position_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.position_teacher', verbose_name='Cargo_Docente'),
        ),
        migrations.AddConstraint(
            model_name='position_teacher',
            constraint=models.UniqueConstraint(fields=('position', 'position_type'), name='position_type_combination'),
        ),
    ]
