# Generated by Django 4.1.2 on 2022-11-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0011_delete_position_teacher'),
        ('administracion', '0014_position_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position_teacher',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='position_teacher',
            name='position_type',
            field=models.CharField(choices=[('Titular', 'Titular'), ('Suplente', 'Suplente')], default='Vacante', max_length=8, verbose_name='Tipo de cargo'),
        ),
        migrations.AlterField(
            model_name='position_teacher',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente'),
        ),
    ]
