# Generated by Django 4.1.2 on 2022-11-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_position_teacher_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_student',
            name='leaving_motive',
            field=models.CharField(choices=[('Finalización de año', 'Finalización de año'), ('Pase', 'Pase'), ('Fallecimiento', 'Fallecimiento')], default='Finalización de año', max_length=30, verbose_name='Motivo de baja'),
        ),
    ]
