# Generated by Django 4.2.1 on 2023-08-14 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('users', '0002_remove_user_username_person_address_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('degree_name', models.CharField(max_length=40, unique=True, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('license_type', models.CharField(max_length=30, null=True, unique=True, verbose_name='Tipo de licencia')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.person')),
                ('cuil', models.CharField(blank=True, max_length=15, null=True)),
                ('seniority_date', models.DateField(blank=True, null=True, verbose_name='Fecha de antiguedad')),
                ('seniority_qty', models.IntegerField(blank=True, null=True, verbose_name='Antiguedd reconocida')),
                ('statistics', models.CharField(choices=[('En actividad', 'En actividad'), ('Tareas pasivas', 'Tareas pasivas'), ('Docentes afectados al JIF pero de otra POF', 'Docentes afectados al JIF pero de otra POF'), ('Docentes del JIF afectados a otro establecimiento', 'Docentes del JIF afectados a otro establecimiento'), ('Sin subvención', 'Sin subvención'), ('Baja', 'Baja'), ('Fuera de actividad', 'InaFuera de actividadctivo'), ('A.T. / Integrador', 'A.T. / Integrador'), ('Par pedagógico / Dep. de dirección privada', 'Par pedagógico / Dep. de dirección privada')], default='En actividad', max_length=50, verbose_name='Estadística')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
            bases=('users.person',),
        ),
        migrations.CreateModel(
            name='Teacher_License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('file', models.FileField(blank=True, null=True, upload_to='documentos/licencias', verbose_name='Documentos/Certificados')),
                ('is_paid', models.BooleanField(default=False, max_length=150, verbose_name='Con goce de sueldo')),
                ('license_from', models.DateField(blank=True, null=True, verbose_name='Licencia desde')),
                ('license_to', models.DateField(blank=True, null=True, verbose_name='Licencia hasta')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.license', verbose_name='Licencia')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Docente_Licencia',
                'verbose_name_plural': 'Docentes_Licencias',
            },
        ),
        migrations.CreateModel(
            name='Teacher_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('file', models.FileField(null=True, upload_to='documentos/alumnos/%Y', verbose_name='Documento')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.documents', verbose_name='Documentación')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Docente_Documento',
                'verbose_name_plural': 'Docentes_Documentos',
            },
        ),
        migrations.CreateModel(
            name='Teacher_Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('file', models.FileField(blank=True, null=True, upload_to='documentos/titulos', verbose_name='Foto/Escaneo de Título')),
                ('graduated_date', models.DateField(blank=True, null=True, verbose_name='Fecha de graduación')),
                ('institution', models.CharField(blank=True, max_length=30, null=True, verbose_name='Otorgado por')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.degree', verbose_name='Título')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Docente_Titulo',
                'verbose_name_plural': 'Docentes_Titulos',
            },
        ),
        migrations.CreateModel(
            name='Salary_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='documentos/recibos', verbose_name='Documentos/Certificados')),
                ('receipt_month', models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default='1', max_length=2, verbose_name='Mes de recibo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Recibo de haber',
                'verbose_name_plural': 'Recibos de haberes',
            },
        ),
        migrations.CreateModel(
            name='Permission_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('motive', models.CharField(max_length=100, verbose_name='Motivo del permiso')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('permission_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('permission_checkin', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('permission_checkout', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('status', models.CharField(choices=[('1', 'Pendiente de autorización'), ('2', 'Aprobado'), ('3', 'Rechazado')], default='1', max_length=2, verbose_name='Estado')),
                ('rejected_motive', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de rechazo')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Solicitud_Permiso',
                'verbose_name_plural': 'Solicitudes_Permisos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDisponibility',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de eliminación')),
                ('week_day', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes')], default='1', max_length=1, verbose_name='Día de la semana')),
                ('init_time', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'historical Disponibilidad horaria',
                'verbose_name_plural': 'historical Disponibilidad horaria',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Disponibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('week_day', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes')], default='1', max_length=1, verbose_name='Día de la semana')),
                ('init_time', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Disponibilidad horaria',
                'verbose_name_plural': 'Disponibilidad horaria',
            },
        ),
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('cbu', models.CharField(max_length=22, unique=True, verbose_name='CBU')),
                ('account_number', models.CharField(blank=True, max_length=22, null=True, verbose_name='Nro de cuenta')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.bank', verbose_name='Banco')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Cuenta_Banco',
                'verbose_name_plural': 'Cuentas_Bancos',
            },
        ),
    ]
