# Generated by Django 4.2 on 2023-04-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_account',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='disponibility',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='historicaldisponibility',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='license',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='permission_request',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='salary_receipt',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='teacher_degree',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='teacher_documents',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='teacher_license',
            name='deleted_date',
        ),
    ]
