# Generated by Django 4.1.2 on 2022-10-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_category_position'),
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(blank=True, max_length=8, null=True, verbose_name='Tipo de cargo')),
                ('condition', models.CharField(blank=True, max_length=15, null=True, verbose_name='Situación')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.position', verbose_name='Cargo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Cargo_Docente',
                'verbose_name_plural': 'Cargos_Docentes',
            },
        ),
    ]
