# Generated by Django 4.1.3 on 2022-11-18 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
        ('administracion', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.person')),
                ('cuil', models.CharField(blank=True, max_length=15, null=True)),
                ('seniority_date', models.DateField(blank=True, null=True, verbose_name='Fecha de antiguedad')),
                ('seniority_qty', models.IntegerField(blank=True, null=True, verbose_name='Antiguedd reconocida')),
                ('statistics', models.CharField(choices=[('En actividad', 'En actividad'), ('Tareas pasivas', 'Tareas pasivas'), ('Docentes afectados al JIF pero de otra POF', 'Docentes afectados al JIF pero de otra POF'), ('Docentes del JIF afectados a otro establecimiento', 'Docentes del JIF afectados a otro establecimiento'), ('Sin subvención', 'Sin subvención'), ('Baja', 'Baja'), ('Fuera de actividad', 'InaFuera de actividadctivo'), ('A.T. / Integrador', 'A.T. / Integrador'), ('Par pedagógico / Dep. de dirección privada', 'Par pedagógico / Dep. de dirección privada')], default='En actividad', max_length=50, verbose_name='Estadística')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
            bases=('users.person',),
        ),
        migrations.CreateModel(
            name='Teacher_License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('file', models.FileField(blank=True, null=True, upload_to='documentos/licencias', verbose_name='Documentos/Certificados')),
                ('is_paid', models.BooleanField(default=False, max_length=150, verbose_name='Con goce de sueldo')),
                ('license_from', models.DateField(blank=True, null=True, verbose_name='Licencia desde')),
                ('license_to', models.DateField(blank=True, null=True, verbose_name='Licencia hasta')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.license', verbose_name='Licencia')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Docente_Licencia',
                'verbose_name_plural': 'Docentes_Licencias',
            },
        ),
        migrations.CreateModel(
            name='Teacher_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('file', models.FileField(null=True, upload_to='documentos/alumnos/%Y', verbose_name='Documento')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.documents', verbose_name='Documentación')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Docente_Documento',
                'verbose_name_plural': 'Docentes_Documentos',
            },
        ),
        migrations.CreateModel(
            name='Teacher_Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('file', models.FileField(blank=True, null=True, upload_to='documentos/titulos', verbose_name='Foto/Escaneo de Título')),
                ('graduated_date', models.DateField(blank=True, null=True, verbose_name='Fecha de graduación')),
                ('institution', models.CharField(blank=True, max_length=30, null=True, verbose_name='Otorgado por')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.degree', verbose_name='Título')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Docente_Titulo',
                'verbose_name_plural': 'Docentes_Titulos',
            },
        ),
        migrations.AddField(
            model_name='salary_receipt',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='permission_request',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='historicaldisponibility',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldisponibility',
            name='teacher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docentes.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='disponibility',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='bank_account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.bank', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='bank_account',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente'),
        ),
    ]
