# Generated by Django 4.1.2 on 2022-10-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_position_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position_teacher',
            name='position_type',
            field=models.CharField(choices=[('Titular', 'Titular'), ('Suplente', 'Suplente')], default='Titular', max_length=8, verbose_name='Tipo de cargo'),
        ),
        migrations.AddConstraint(
            model_name='position_teacher',
            constraint=models.UniqueConstraint(fields=('position', 'position_type'), name='position_type_combination'),
        ),
    ]
