# Generated by Django 4.1.2 on 2022-10-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_alter_position_teacher_position_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position_teacher',
            name='delete_motive',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo de baja'),
        ),
    ]
