# Generated by Django 4.1.2 on 2022-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_position_teacher_delete_motive'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_documents',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documentos/docentes/%Y', verbose_name='Documento'),
        ),
    ]
