# Generated by Django 4.1.2 on 2022-10-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0005_license_teacher_documents_file_teacher_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_license',
            name='is_paid',
            field=models.BooleanField(default=False, max_length=150, verbose_name='Con goce de sueldo'),
        ),
    ]
