# Generated by Django 4.1.2 on 2022-10-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0005_license_teacher_documents_file_teacher_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_license',
            name='created_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='teacher_license',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documentos/licencias', verbose_name='Documentos/Certificados'),
        ),
        migrations.AlterField(
            model_name='teacher_license',
            name='is_paid',
            field=models.BooleanField(default=False, max_length=150, verbose_name='Con goce de sueldo'),
        ),
        migrations.CreateModel(
            name='Salary_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='documentos/recibos', verbose_name='Documentos/Certificados')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de registro')),
                ('receipt_month', models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default='1', max_length=2, verbose_name='Mes de recibo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Recibo de haber',
                'verbose_name_plural': 'Recibos de haberes',
            },
        ),
    ]
