# Generated by Django 4.1.2 on 2022-10-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_bank'),
        ('docentes', '0006_alter_teacher_license_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbu', models.CharField(max_length=22, unique=True, verbose_name='CBU')),
                ('account_number', models.CharField(blank=True, max_length=22, null=True, verbose_name='Nro de cuenta')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('state', models.BooleanField(default=True, max_length=1, verbose_name='Vigente')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.bank', verbose_name='Banco')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Cuenta_Banco',
                'verbose_name_plural': 'Cuentas_Bancos',
            },
        ),
    ]
