# Generated by Django 4.1.2 on 2022-10-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0006_alter_teacher_license_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_license',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documentos/licencias', verbose_name='Documentos/Certificados'),
        ),
    ]
