# Generated by Django 4.1.2 on 2022-10-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0007_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(max_length=100, verbose_name='Motivo del permiso')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('permission_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('permission_checkin', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('permission_checkout', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('status', models.CharField(choices=[('1', 'Pendiente de autorización'), ('2', 'Aprobado'), ('3', 'Rechazado')], default='1', max_length=2, verbose_name='Estado')),
                ('rejected_motive', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de rechazo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.teacher', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Solicitud_Permiso',
                'verbose_name_plural': 'Solicitudes_Permisos',
            },
        ),
    ]
