# Generated by Django 4.1.2 on 2022-11-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_position_teacher_and_more'),
        ('docentes', '0010_historicaldisponibility_disponibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position_Teacher',
        ),
    ]
