# Generated by Django 4.1.3 on 2022-11-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('payment_type', models.CharField(choices=[('1', 'Cuota mensual'), ('2', 'Pago de matrícula')], default='1', max_length=1, verbose_name='Tipo de pago')),
                ('unit_amount', models.IntegerField(blank=True, null=True, verbose_name='Monto unitario')),
                ('brothers_qty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1, verbose_name='Cantidad de hermanos')),
                ('brothers_discount', models.IntegerField(blank=True, null=True, verbose_name='Descuento por hermanos')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Payment_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
            ],
            options={
                'verbose_name': 'Pago_Alumno',
                'verbose_name_plural': 'Pagos_Alumnos',
            },
        ),
    ]
