# Generated by Django 4.2.1 on 2023-08-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='deleted_date',
            field=models.DateField(null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='payment_student',
            name='deleted_date',
            field=models.DateField(null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='student_documents',
            name='deleted_date',
            field=models.DateField(null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='student_tutor',
            name='deleted_date',
            field=models.DateField(null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='student_withdraw_authorized',
            name='deleted_date',
            field=models.DateField(null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='withdraw_authorized',
            name='deleted_date',
            field=models.DateField(null=True, verbose_name='Fecha de eliminación'),
        ),
    ]
