# Generated by Django 4.2 on 2023-04-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='payment_student',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='student_documents',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='student_tutor',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='student_withdraw_authorized',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='withdraw_authorized',
            name='deleted_date',
        ),
    ]
