# Generated by Django 4.2.1 on 2023-08-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_payment_deleted_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='brothers_discount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='brothers_qty',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='unit_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Importe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='file',
            field=models.FileField(null=True, upload_to='documentos/alumnos/%Y', verbose_name='Comprobante'),
        ),
    ]
